Iter23
shevchukeugeni/metrics pull request #27
Opened 2024-05-02 09:39 UTC by shevchukeugeni

2024-05-03 15:20 UTC, tmvrus requested changes
есть замечания

2024-05-06 10:18 UTC, shevchukeugeni commented on cmd/server/main.go
> +		pkBlock, _ = pem.Decode(privateKeyPEM)
Данный метод не возвращает ошибки. Добавил проверку результата на nil

// Decode will find the next PEM formatted block (certificate, private key
// etc) in the input. It returns that block and the remainder of the input. If
// no PEM data is found, p is nil and the whole of the input is returned in
// rest.
func Decode(data []byte) (p *Block, rest []byte)

2024-05-06 10:18 UTC, shevchukeugeni commented on cmd/server/main.go
> +	if err := srv.ListenAndServe(); err != http.ErrServerClosed {
Взял данный код из обучающих материалов спринта

2024-05-06 10:25 UTC, shevchukeugeni commented on internal/server/router.go
> +			io.Copy(w, r.Body)
Сделал по аналогии с signMiddleware из спринта 4 инкремента 14. Там было явно указано, что нужно "отбрасывать полученные данные". В прошлом код ревью вопросов по данному моменту не было, подумал что какой-то вычурный элемент обучения.

2024-05-06 11:15 UTC, shevchukeugeni commented
Все указанные выше замечания исправлены. Треды оставлены для обсуждения

2024-05-06 15:50 UTC, tmvrus commented on cmd/server/main.go
> +	if err := srv.ListenAndServe(); err != http.ErrServerClosed {
так может тебя там специально сбивают, что бы студенты не занимались копированием

2024-05-06 16:09 UTC, tmvrus approved these changes

2024-05-14 07:36 UTC, merged