Iter25
shevchukeugeni/metrics pull request #28
Opened 2024-05-14 18:41 UTC by shevchukeugeni

2024-05-17 14:30 UTC, tmvrus requested changes

2024-05-17 14:30 UTC, tmvrus commented on internal/types/common.go
> +	}
ошибку надо хотя бы логирвать, иначе очень долго после выяснять почему адрес не отправляется

2024-05-17 14:30 UTC, tmvrus commented on proto/metrics.proto
> +    GAUGE = 0;
лучше добавить DEFAULT=0 чт бы отличать два состояния - когда данные добавили а когда нет

2024-05-17 14:30 UTC, tmvrus commented on internal/server/storage.go
> +type MetricStorage interface {
мы уже обсуждали что нужно использовать контекст
https://github.com/shevchukeugeni/metrics/pull/18#pullrequestreview-1842149168

2024-05-17 14:30 UTC, tmvrus commented on cmd/agent/main.go
> +		_, innerErr = req.SetHeader("X-Real-IP", types.GetLocalIP()).SetBody(cdata).Post(fmt.Sprintf("http://%s/updates/", cfg.ServerAddr))
заголовок X-Real-IP всегда посылается, даже если адрес получить не удлось, это будет приводить к ошибке при проверке на сервере

2024-05-17 14:30 UTC, tmvrus commented on cmd/agent/main.go
> +	var mtrcs []*pb.Metric
можно заранее указать размер, поскольку он известен

2024-05-17 14:30 UTC, tmvrus commented on cmd/agent/main.go
> +		log.Println("Unable to connect", err)
тут работа ф-и продолжится, что придет к ошибке или даже панике

2024-05-17 14:30 UTC, tmvrus commented on cmd/agent/main.go
> +	conn, err := grpc.Dial(cfg.GrpcServerAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
устанавливать и закрывать соединение при каждой отправке grpc-запроса это антипаттерн, обычно создают соединение при старте программы и пользуются им постоянно

2024-05-17 14:30 UTC, tmvrus commented on cmd/agent/main.go
> +		*sw++
использовать счетчик в разных горутинах небезопасно

2024-05-17 14:30 UTC, tmvrus commented on cmd/agent/main.go
> +		if *sw%2 == 0 {
очень оригинально, но зачем?
почему бы просто не отправлять по grpc если передали grpc?

2024-05-17 14:30 UTC, tmvrus commented on cmd/agent/main.go
> +	// create for alternation of request types
нет никакой гарантии что это будет работать так как задумано

2024-05-21 11:22 UTC, tmvrus approved these changes

2024-05-21 12:38 UTC, shevchukeugeni commented on cmd/agent/main.go
> +	i := 0
мы создали массив сразу известной нам длины, через append его теперь не заполнить

2024-05-21 13:09 UTC, tmvrus commented on cmd/agent/main.go
> +	i := 0
это потому что создается он вот так make([]*pb.Metric, len(metrics.Counter)+len(metrics.Gauge))
а если сделать вот так make([]*pb.Metric, 0, len(metrics.Counter)+len(metrics.Gauge))
то append будет работать

2024-05-22 03:45 UTC, merged